import { EmotionCategory, EmotionWord } from './types';

// This is a simplified emotion lexicon. In a production app, you'd want a much more comprehensive database
export const emotionLexicon: EmotionWord[] = [
  // Joy
  { word: 'happy', category: 'joy', intensity: 0.8 },
  { word: 'excited', category: 'joy', intensity: 0.9 },
  { word: 'grateful', category: 'joy', intensity: 0.7 },
  { word: 'wonderful', category: 'joy', intensity: 0.8 },
  { word: 'delighted', category: 'joy', intensity: 0.8 },
  { word: 'cheerful', category: 'joy', intensity: 0.7 },
  { word: 'elated', category: 'joy', intensity: 0.9 },
  { word: 'content', category: 'joy', intensity: 0.6 },
  { word: 'optimistic', category: 'joy', intensity: 0.7 },
  { word: 'joyful', category: 'joy', intensity: 0.9 },
  { word: 'pleased', category: 'joy', intensity: 0.6 },
  { word: 'thrilled', category: 'joy', intensity: 0.9 },
  { word: 'ecstatic', category: 'joy', intensity: 1.0 },
  { word: 'blissful', category: 'joy', intensity: 0.9 },
  { word: 'upbeat', category: 'joy', intensity: 0.7 },
  
  // Sadness
  { word: 'sad', category: 'sadness', intensity: 0.7 },
  { word: 'disappointed', category: 'sadness', intensity: 0.6 },
  { word: 'lonely', category: 'sadness', intensity: 0.8 },
  { word: 'hopeless', category: 'sadness', intensity: 0.9 },
  { word: 'missing', category: 'sadness', intensity: 0.5 },
  { word: 'melancholy', category: 'sadness', intensity: 0.7 },
  { word: 'gloomy', category: 'sadness', intensity: 0.6 },
  { word: 'heartbroken', category: 'sadness', intensity: 0.9 },
  { word: 'devastated', category: 'sadness', intensity: 1.0 },
  { word: 'depressed', category: 'sadness', intensity: 0.9 },
  { word: 'dejected', category: 'sadness', intensity: 0.7 },
  { word: 'miserable', category: 'sadness', intensity: 0.8 },
  { word: 'sorrowful', category: 'sadness', intensity: 0.8 },
  { word: 'downhearted', category: 'sadness', intensity: 0.7 },
  { word: 'blue', category: 'sadness', intensity: 0.5 },

  // Anger
  { word: 'angry', category: 'anger', intensity: 0.8 },
  { word: 'frustrated', category: 'anger', intensity: 0.6 },
  { word: 'annoyed', category: 'anger', intensity: 0.5 },
  { word: 'furious', category: 'anger', intensity: 0.9 },
  { word: 'irritated', category: 'anger', intensity: 0.4 },
  { word: 'enraged', category: 'anger', intensity: 1.0 },
  { word: 'livid', category: 'anger', intensity: 0.9 },
  { word: 'outraged', category: 'anger', intensity: 0.8 },
  { word: 'resentful', category: 'anger', intensity: 0.7 },
  { word: 'bitter', category: 'anger', intensity: 0.7 },
  { word: 'hostile', category: 'anger', intensity: 0.8 },
  { word: 'aggravated', category: 'anger', intensity: 0.6 },
  { word: 'incensed', category: 'anger', intensity: 0.8 },
  { word: 'infuriated', category: 'anger', intensity: 0.9 },

  // Fear
  { word: 'afraid', category: 'fear', intensity: 0.7 },
  { word: 'worried', category: 'fear', intensity: 0.6 },
  { word: 'anxious', category: 'fear', intensity: 0.8 },
  { word: 'nervous', category: 'fear', intensity: 0.5 },
  { word: 'scared', category: 'fear', intensity: 0.7 },
  { word: 'terrified', category: 'fear', intensity: 1.0 },
  { word: 'panicked', category: 'fear', intensity: 0.9 },
  { word: 'distressed', category: 'fear', intensity: 0.8 },
  { word: 'overwhelmed', category: 'fear', intensity: 0.8 },
  { word: 'uneasy', category: 'fear', intensity: 0.4 },
  { word: 'insecure', category: 'fear', intensity: 0.6 },
  { word: 'apprehensive', category: 'fear', intensity: 0.6 },
  { word: 'stressed', category: 'fear', intensity: 0.7 },
  { word: 'tense', category: 'fear', intensity: 0.6 },

  // Surprise
  { word: 'surprised', category: 'surprise', intensity: 0.7 },
  { word: 'amazed', category: 'surprise', intensity: 0.8 },
  { word: 'shocked', category: 'surprise', intensity: 0.9 },
  { word: 'unexpected', category: 'surprise', intensity: 0.6 },
  { word: 'astonished', category: 'surprise', intensity: 0.8 },
  { word: 'bewildered', category: 'surprise', intensity: 0.6 },
  { word: 'stunned', category: 'surprise', intensity: 0.8 },
  { word: 'flabbergasted', category: 'surprise', intensity: 0.9 },
  { word: 'perplexed', category: 'surprise', intensity: 0.5 },
  { word: 'startled', category: 'surprise', intensity: 0.7 },

  // Calm
  { word: 'calm', category: 'calm', intensity: 0.7 },
  { word: 'peaceful', category: 'calm', intensity: 0.6 },
  { word: 'relaxed', category: 'calm', intensity: 0.7 },
  { word: 'serene', category: 'calm', intensity: 0.8 },
  { word: 'tranquil', category: 'calm', intensity: 0.8 },
  { word: 'composed', category: 'calm', intensity: 0.6 },
  { word: 'centered', category: 'calm', intensity: 0.7 },
  { word: 'balanced', category: 'calm', intensity: 0.6 },

  // Neutral
  { word: 'okay', category: 'neutral', intensity: 0.3 },
  { word: 'fine', category: 'neutral', intensity: 0.3 },
  { word: 'normal', category: 'neutral', intensity: 0.2 },
  { word: 'average', category: 'neutral', intensity: 0.2 },
  { word: 'regular', category: 'neutral', intensity: 0.2 },
  { word: 'indifferent', category: 'neutral', intensity: 0.3 },
  { word: 'neutral', category: 'neutral', intensity: 0.3 },
  { word: 'stable', category: 'neutral', intensity: 0.4 },
  { word: 'steady', category: 'neutral', intensity: 0.4 },
  { word: 'unchanged', category: 'neutral', intensity: 0.2 },
];

// Common activity tags that might correlate with emotions (aligned with UI)
export const activityTags = [
  'Exercise',
  'Work',
  'Social',
  'Family',
  'Hobby',
  'Rest',
  'Entertainment',
  'Learning',
  'Chores',
  'Nature',
  'Travel',
  'Shopping',
  'Health',
  'Food',
  'Sleep',
  'Friends',
  'Study',
  'Meditation',
  'Reading',
  'Music',
] as const;

// Emotion-activity correlations for tag suggestions
export const emotionActivityCorrelations: Record<EmotionCategory, string[]> = {
  joy: ['Exercise', 'Friends', 'Hobby', 'Music', 'Nature', 'Social', 'Entertainment'],
  sadness: ['Meditation', 'Music', 'Reading', 'Nature', 'Rest'],
  anger: ['Exercise', 'Meditation', 'Music', 'Rest'],
  fear: ['Meditation', 'Friends', 'Reading', 'Rest', 'Health'],
  surprise: ['Social', 'Travel', 'Shopping', 'Entertainment'],
  calm: ['Meditation', 'Nature', 'Reading', 'Music', 'Rest'],
  neutral: ['Work', 'Study', 'Food', 'Learning'],
};
